# Generated by Django 3.1.1 on 2020-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(max_length=1000)),
                ('deslike', models.IntegerField(max_length=1000)),
                ('total', models.IntegerField(max_length=1000)),
                ('gif', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'loefa',
            },
        ),
    ]
